title: Ting-Yu, Liang
logo: /assets/img/profile.png
description: Bachelor of Engineering in Computer Science, with Minor in Business at The Hong Kong University of Science and Technology (2020 - 2024)
show_downloads: false
theme: jekyll-theme-minimal
